INSERT INTO "ADMIN".CONDICION (IDCONDICION, DESCRIPCION, NOMBRE) VALUES ('1', 'Condicion1', 'condicion1');
INSERT INTO "ADMIN".TIPOINMUEBLE (IDTIPOINMUEBLE, NOMBRETIPO) VALUES ('1', 'tipo1');
INSERT INTO "ADMIN".DEPARTAMENTO (IDDEPARTAMENTO, NOMBREDEPARTAMENTO) VALUES ('1', 'Godoy Cruz');
INSERT INTO "ADMIN".LOCALIDAD (IDLOCALIDAD, CODIGOPOSTAL, NOMBRELOCALIDAD) VALUES ('1', 5500, 'localidad1');
INSERT INTO "ADMIN".DEPARTAMENTO_LOCALIDAD (DEPARTAMENTO_IDDEPARTAMENTO, LOCALIDADES_IDLOCALIDAD) VALUES ('1', '1');
INSERT INTO "ADMIN".PROVINCIA (IDPROVINCIA, ABREVIATURA, NOMBREPROVINCIA) VALUES ('1', 'MZA', 'Mendoza');
INSERT INTO "ADMIN".PROVINCIA_DEPARTAMENTO (PROVINCIA_IDPROVINCIA, DEPARTAMENTO_IDDEPARTAMENTO) VALUES ('1', '1');
INSERT INTO "ADMIN".DIRECCION (IDDIRECCION, NOMBRECALLE, NRODEPARTAMENTO, NROPISO, NUMERO, OBSERVACION, DEPARTAMENTO_IDDEPARTAMENTO, LOCALIDAD_IDLOCALIDAD, PROVINCIA_IDPROVINCIA) VALUES ('1', 'calle1', '1', '2', '111', 'Obs', '1', '1', '1');
INSERT INTO "ADMIN".DIRECCION (IDDIRECCION, NOMBRECALLE, NRODEPARTAMENTO, NROPISO, NUMERO, OBSERVACION, DEPARTAMENTO_IDDEPARTAMENTO, LOCALIDAD_IDLOCALIDAD, PROVINCIA_IDPROVINCIA) VALUES ('2', 'Otra Calle', '2', '2', '123', 'Obs', '1', '1', '1');
INSERT INTO "ADMIN".ESTADOINMUEBLE (IDESTADOINMUEBLE, ESTADO) VALUES ('1', '1');
INSERT INTO "ADMIN".HISTORICOESTADOINMUEBLE (IDHISTORICOESTADOINMUEBLE, FECHAFIN, FECHAINCIO, ESTADOINMUEBLE_IDESTADOINMUEBLE) VALUES ('1', '2011-10-25', '2011-10-05', '1');
INSERT INTO "ADMIN".INMUEBLE (IDINMUEBLE, ANIOCONSTRUCCION, CODINMUEBLE, FECHAALTA, FOTOS, IMPORTEMENSUALIDAD, NROPLANTAS, PRECIOPESOS, SUPERFICIECUBIERTA, SUPERFICIETOTAL, TIPOINMUEBLE_IDTIPOINMUEBLE, DIRECCION_IDDIRECCION) VALUES ('1', 1960, '1', '2011-08-23', '', 1000.0, 1, '125000', '200', '500', '1', '1');
INSERT INTO "ADMIN".INMUEBLE (IDINMUEBLE, ANIOCONSTRUCCION, CODINMUEBLE, FECHAALTA, FOTOS, IMPORTEMENSUALIDAD, NROPLANTAS, PRECIOPESOS, SUPERFICIECUBIERTA, SUPERFICIETOTAL, TIPOINMUEBLE_IDTIPOINMUEBLE, DIRECCION_IDDIRECCION) VALUES ('2', 1970, '2', '2011-08-23', '', 2000.0, 1, '505000', '300', '800', '1', '2');
INSERT INTO "ADMIN".INMUEBLE_HISTORICOESTADOINMUEBLE (INMUEBLE_IDINMUEBLE, HISTORICOSESTADOSINMUEBLES_IDHISTORICOESTADOINMUEBLE) VALUES ('1', '1');

INSERT INTO "ADMIN".USUARIO (IDUSUARIO, APELLIDO, CONTRASENIA, EMAIL, NOMBRE, NOMBREUSUARIO) VALUES ('1', 'Ape', 'e10adc3949ba59abbe56e057f20f883e', 'algo@algo.com', 'Nom', 'user');
